[package]
name = "consul-example"
version = "0.1.0"
authors = ["T.J. Telan <t.telan@gmail.com>"]
edition = "2018"

[dependencies]
#consul = { path = "./consul-rust" }
consul = "0.2.0"
dotenv = "0.9.0"
